
server.port=8080


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/curso_springboot}
spring.datasource.username=${DB_USERNAME:devdb}
spring.datasource.password=${DB_PASSWORD:a1b2c3d4}


spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.open-in-view=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.main.allow-circular-references=true


spring.jpa.show-sql=true


logging.level.web=DEBUG

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG
